### PR TITLE
overwriting of default files

### PR DESCRIPTION
**Pull request by Brijeshkrishna**
--overwrite option overwrite the default file with user created file

### CODE REVIEW

**Comment by Foxboron** [comment]
Can you please write the use-case for this?

**Comment by Brijeshkrishna** [comment]
Error: failed to commit transaction (conflicting files)
calamares-git: /home/user/Desktop/distro/work/x86_64/airootfs/etc/calamares/modules/mount.conf exists in filesystem
calamares-git: /home/user/Desktop/distro/work/x86_64/airootfs/etc/calamares/modules/partition.conf exists in filesystem
Errors occurred, no packages were upgraded.

==> ERROR: Failed to install packages to new root.

This error can be avoided

**Comment by Foxboron** [comment]
Why would those files exist if you are installing the package? This seems like poor packaging and I'm inclined to include features into `pacstrap` to work around that.

**Comment by Brijeshkrishna** [comment]
These files are for overwriting the default configuration file of the package.

**Comment by Foxboron** [comment]
It's a better idea to install the system, then work on the files that have been installed.

**Comment by Brijeshkrishna** [comment]
for the default customized config file.

**Comment by Brijeshkrishna** [comment]
for this reason
https://youtu.be/tSGGBbJBgvk?t=1405

**Comment by Foxboron** [comment]
Not accepting this change as-is. It doesn't make sense to add this to the non-interactive line and I still do not understand the issue it's trying to solve.

**Pull request closed without merging**
